---
services:

  minecraft-server:  # https://github.com/itzg/docker-minecraft-server
    environment:
      UID: 1027
      GID: 1027
      ENABLE_WHITELIST: 'true'
      ALLOW_FLIGHT: 'true'
      ALLOW_CHEATS: 'true'
      # DEBUG: 'true'
      ENABLE_COMMAND_BLOCK: 'true'
      EULA: 'true'
      MAX_PLAYERS: '5'
      # MODE: survival
      ONLINE_MODE: 'false'
      VERSION: 1.21
    image: itzg/minecraft-server
    ports: [25565:25565, 25575:25575]
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes: [./data:/data]
